### PR TITLE
Add scripting API palettes

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add palettes containing the scripting APIs to the scripting API build.

### What does this Pull Request _not_ accomplish?

There are currently no custom icons for the palette items; I would prefer to add those in a separate review.

The top level "VeriStand Custom Device Scripting APIs" palette item will need to be installed by a separate nipkg; it is not part of this review.

### Why should this Pull Request be merged?

The scripting API is currently being installed to vi.lib but is not discoverable.

### What testing has been done?

Copied built scripting APIs into `vi.lib/addons/VeriStand Custom Device Scripting APIs` and confirmed they appear as expected.

---

- image
  - image
  - image
    - image
  - image

---

- image
  - image
  - image

### CODE REVIEW

**Comment by rtzoeller** [comment]
@mdcerna Excellent point.

One concern I have is that the VI names are long enough that even without the `.vi` suffix they will force an ellipsis. Do we want to remove e.g. the "SLSC Switch" and "Routing and Faulting" parts of the VI names, since that is implied by the owning palette?

**Comment by csjall** [comment]
> @mdcerna Excellent point.
> 
> One concern I have is that the VI names are long enough that even without the `.vi` suffix they will force an ellipsis. Do we want to remove e.g. the "SLSC Switch" and "Routing and Faulting" parts of the VI names, since that is implied by the owning palette?

Short names without Routing and Faulting or SLSC Switch prefix sounds good. For example, "Set SLSC Switch Topology.vi" would become "Set Topology".

**Comment by mdcerna** [comment]
- [ ] States palette feedback.  Should be called State Configuration or States and Connections

- [ ] States functions should be renamed, but for now we can use the following as their Short names:
Add State to Routing Channel     **Add State**
Get State from Routing Channel     **Get State**
Remove Routing Channel State     **Remove State**

Set State Connections     **Set Connections**
Add Connection to State     **Add Connection**
Remove State Connection     **Remove Connection**

- [ ] Feedback on State Configuration layout. With short names and Get under a Set, when appropriate:
image

**Comment by mdcerna** [comment]
- [ ] Short name/renaming:

Poly VI: **Get Routing Channel ID**
>by Name
>All

Get Routing Channel Configuration     **Get Routing Channel**
Set Routing Channel State Configurations     **Set State Configurations**
Get Routing Channel State Configurations     **Get State Configurations**
Set Routing Channel Initial State    **Set Initial State**
Get Routing Channel Initial State    **Get Initial State**
Set Routing Channel Description    **Set Channel Description**
Set Routing Channel Name    **Set Channel Name**
Get Routing Channel State-Value Table     **Get State-Value Table**


**Routing Channel Mockup**
image

**Pull request merged**
