### PR TITLE
Add producer to Routing and Faulting engine

### PR DESCRIPTION
**Pull request by buckd**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Initializes the Producer for the routing and faulting custom device to send messages to all switch consumer custom devices.

- The producer is initialized with all of the consumer names.
- Input channels are set up so when value changes occur, disconnect messages will be sent followed by connect messages.
- Initial state will be sent to all consumers once the logic for creating the connect messages exists.
- During shutdown, disconnect all and shutdown messages are sent to all consumers.

### Why should this Pull Request be merged?

This is the basis for all communication between the routing and faulting custom device and any SLSC Switch custom devices in the system.

### What testing has been done?

- Ensured all SLSC Switch consumers are correctly enumerated.
- Ensured shutdown of the producer is handled correctly. **The SLSC Switch engine may need to remove the check for shutdown in the consumer loop to ensure it handles shutdown correctly.**
- Tested the writing outputs works correctly by manually creating the channels and hard coding indices. Once the status channels are added to initialization of the custom device and compiled correctly, channel writing will just work.

### CODE REVIEW

**Comment by rtzoeller** [comment]
- [ ] Should `Shutdown Producer.vi` run unconditionally, instead of checking incoming error? We stop the data loop in the case of an error (e.g. if `Engine Main.vi` errors), but the producer will not shut down.

**Comment by buckd** [comment]
>Should `Shutdown Producer.vi` run unconditionally, instead of checking incoming error? We stop the data loop in the case of an error (e.g. if `Engine Main.vi` errors), but the producer will not shut down.

Yes, it should run unconditionally. Also, `Send Shutdown All.vi` should be pulled outside the loop and run just before `Shutdown Producer.vi`. It should also run unconditionally.

**Comment by csjall** [comment]
- [ ] `RT Driver VI.vi`: Clean up wiring. Boolean wire overlaps status unbundle. Engine data should enter/exit on left/right, not top.
image
- [ ] `Send Shutdown All.vi`: Do not eat the errors. Merge the errors in to error out.
image
- [ ] `Update Initial States.vi`, `Update States.vi`: Why do we cache the disconnect and connect messages in engine data? Create and send the message without caching the message. The only thing we should cache is the previous routing channel value. The messages are only used within the same loop iteration and do need to be stored for the next iteration.
image

**Comment by rtzoeller** [comment]
https://github.com/ni/niveristand-slsc-switch-message-library/pull/6

**Comment by csjall** [comment]
Create an issue to remove connect and disconnect messages from engine cluster.

**Pull request merged**
