### PR TITLE
Pass around indices into a buffer of connection strings to avoid copies

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

During message generation, pass around indices into a buffer of connection strings to avoid copies.

### Why should this Pull Request be merged?

We should avoid making string copies as much as possible during message generation, which we can do by compiling them into a flat buffer and passing the indices into this buffer around instead.

### What testing has been done?

Updated and ran unit tests, deployed and confirmed hardware is correctly controlled.

### CODE REVIEW

**Comment by rtzoeller** [comment]
I need to resolve merge conflicts, and want to do some allocation profiling to ensure that we are getting the full benefits out of this change. That said, I would prefer to get eyes on it early.

**Comment by rtzoeller** [comment]
Finished profiling, I'm pretty happy with the results overall. Merge conflicts should be resolved, so this is ready for review.

**Comment by csjall** [comment]
- [ ] Check result of Search 1D array before indexing array. Right now you will unconditionally index the connection list array. I recommend moving the code into default case for the search result.
image
- [ ] Remove Number to Decimal String and used built in format string to convert number.
`The specified state "%d" is not valid for route "%s".`
image
- [ ] Replace the array building with a shift register that dynamically adds compiled connection indices to the array. This removes the unnecessary allocations in the case where the state did not change.

**Comment by rtzoeller** [comment]
@csjall feedback addressed.

**Comment by csjall** [comment]
- [ ] Use Build Array with concatenate inputs option.
image

**Comment by csjall** [comment]
Submit once we have a successful PR build.

**Pull request merged**
