### PR TITLE
Add localization text in niveristand-routing-and-faulting-custom-device-slsc-switch control page

### PR DESCRIPTION
**Pull request by Palshini**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/main/CONTRIBUTING.md).

TODO: Include high-level description of the changes in this pull request.
As part of User Story (https://ni.visualstudio.com/DevCentral/_workitems/edit/2665528/) We are trying to include localization description for Chinese, German, Japanese, French, Korean languages for different VeriStand third party products.

TODO: Justify why this contribution should be part of the project.
Taken reference from VeriStand control page (‪\argo\ni\nipkg\pool\ni-v\ni-veristand-2024\24.0.0\24.0.0.49451-0+f299\ni-veristand-2024_24.0.0.49451-0+f299_windows_x64.nipkg.control) and edited niveristand-routing-and-faulting-cd-slsc-switch control page accordingly.

TODO: Detail what testing has been done to ensure this submission meets requirements.
Testing is in progress

### CODE REVIEW

**Review by buckd — DISMISSED** [review]

**Comment by buckd** [comment]
@Palshini This looks like the wrong file. You should be updating `control_slsc_switch` instead.

**Review by buckd — CHANGES_REQUESTED** [review]
Revert `control_ni_switch` and update `control_slsc_switch`.

**Comment by Palshini** [comment]
@buckd https://github.com/ni/niveristand-routing-and-faulting-custom-device/pull/296/files I have corrected the file and created this new PR.

**Comment by Palshini** [comment]
@buckd. Closed this PR as I have created new one.

**Pull request closed without merging**
