### PR TITLE
Use short module name in connections editor

### PR DESCRIPTION
**Pull request by mdcerna**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Users will now see the shortened module name, and no reference to Resource in the following:
* State Connections array
* Edit Connection dialog (Module pulldown)

In addition, the Routing Channel Page diagram has been cleaned up by forming an Editor State cluster with system definition information including:
* Alias Mapping
* Possible Connections (HW API)
* Controller name (for reforming full Module name per connection)

### Why should this Pull Request be merged?

Way better user experience to view and select the shortened Module name.

### What testing has been done?

Manual build and interactive test of the Routing Channel Editor and inspection of the resulting system def file.

### CODE REVIEW

**Comment by rtzoeller** [comment]
- [ ] I am seeing an error when attempting to delete a connection 
image

**Comment by rtzoeller** [comment]
- [ ] Adding a new connection by hitting the add button results in an empty dialog.
image
image

**Comment by csjall** [comment]
- [ ] `Get Possible Connections (HW).vi`: Cache the UI friendly and full module path. Use the UI friendly module path to format the UI. Use the full module path to update the system definition.
image

- [ ] `Configure Connection Dialog.vi`: Use cached module path instead of re-formatting it.
image

- [ ] `Handle Connections Value Change.vi`: Use cached module path instead of re-formatting it.
image

- [ ] Remove `Format Connection UI to Connection.vi`.

**Comment by csjall** [comment]
- [ ] `Initialize Channel Editor State.vi`: Remove dead code.
image
- [ ] `Possible Connections.ctl`: The module and module path are ambiguously named. Disambiguate the two with explicit naming. Use "Formatted Module Path" or "Short Module Path" for the formatted module path.
- [ ] `Shared\Routing and Faulting Hardware API\Properties\Get Module Path.vi`: Rename `Resource` terminal to `Module Path` to be consistent with VI name and function.
- [ ]

**Pull request merged**
