### PR TITLE
Connections Editor

### PR DESCRIPTION
**Pull request by mdcerna**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Implements the ability to edit Connections of a selected State.
Features:
* Add connection using + button in lower left
* Add connection by clicking in un-populated Connections area
* Delete connection by clicking on the - key to the right of each row

* Click on a connection row to bring up editing dialog
 Editing dialog populated with selected row
 Resource pull-down is populated with currently-available switching modules
 Resource change will filter valid Source (with Aliases listed first)
 Source change will filter valid Destinations (with Aliases listed first)

* Fixes the unexpected side-effect that Set Connections re-orders the State list (edited State moved to the end)

### Why should this Pull Request be merged?

A full System Explorer editor requires the editing of each State's connections

### What testing has been done?

Manual build and interactive test

### CODE REVIEW

**Comment by buckd** [comment]
- [ ] The border in the dialog should be a System Recessed Frame. For any UI element that has a System version, we should use that.
image

**Comment by mdcerna** [comment]
> * [ ]  Aliases are not listed in the source or destination drop downs in the dialog
I believe the new module path format (instead of Resource) is being parsed incorrectly.  Working on a fix that will likely address the other issues.

**Comment by mdcerna** [comment]
Donovan, please see latest: addressed your feedback and simplified connection edits by using an Edit Connections (ellipsis) button
image

**Comment by csjall** [comment]
- [ ] Veristand 2019 is doing _funny_ things when I click the "+" button for a new connection. The system explorer is pushed back in z order, the project window is pushed forward in z order, and the dialog is placed on top. Ideally the dialog should be parented to the System Explorer. We should talk to Patrick about z-ordering with NXG shell.
image
- [ ] The dialog is not properly formatted. The left edge of the recessed frame should not be flush with the dialog.
image
- [ ] The combo box for the hardware resource is too short. I cannot see which slot I am using.

**Comment by mdcerna** [comment]
> * [x]  I cannot currently add new state or edit information about an existing state. Is that part of this review too?
I am working on a subsequent user story for Add and Remove State.

**Comment by mdcerna** [comment]
> Delete `Find Changed Connections Array Element.vi`. This code is identical to `Find Changed Array Element.vi`. Make `Find Changed Array Element` a malleable VI and use that instead.
After making all changes, the build kept failing, stuck on the "bad VI" issue with the malleable VI.  
My temporary solution is to use 2 VIs, 1 for each element type.

**Comment by csjall** [comment]
- [ ] The tabbing order on the dialog is confusing. Hide any control/indicator that are not used and set the tab order (top left to bottom right)
image

**Pull request merged**
