### PR TITLE
Initial SLSC Switch read-only main page

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add an initial read-only main page for the SLSC Switch custom device.

### Why should this Pull Request be merged?

This adds the ability to view information for the custom device in the system explorer.

### What testing has been done?

Opened a scripted system definition and confirmed the information displayed correctly.

### CODE REVIEW

**Comment by csjall** [comment]
- [ ] `Main Page.vi`: Remove name control and event handler. Our current mockups do not include the name of the module.
image
- [ ] `Initialize Main Page.vi`: Wire main page controls on the left instead of the top. As a general rule of thumb you want to fill terminals on left before going to top and bottom.
image
- [ ] `Initialize Main Page.vi`: Mike is working on a revised Scripting API that returns all the properties, including description, for the SLSC Switch Module. Use the updated scripting method instead of calling `Get Item Description.vi`.
image

**Comment by rtzoeller** [comment]
> - [ ] Initialize Main Page.vi: Wire main page controls on the left instead of the top. As a general rule of thumb you want to fill terminals on left before going to top and bottom.

My thought process here has been that we typically end up passing these clusters of references into multiple VIs in addition to initialize, and that many of these take additional parameters. IMO it reduces mental overhead to always have the control references terminal in the same place, e.g. the top, where it is out of the way of additional inputs.

**Comment by rtzoeller** [comment]
> - [ ] Initialize Main Page.vi: Mike is working on a revised Scripting API that returns all the properties, including description, for the SLSC Switch Module. Use the updated scripting method instead of calling Get Item Description.vi.

Blocked on #17 for now.

**Comment by csjall** [comment]
> > * [ ]  Initialize Main Page.vi: Mike is working on a revised Scripting API that returns all the properties, including description, for the SLSC Switch Module. Use the updated scripting method instead of calling Get Item Description.vi.
> 
> Blocked on #17 for now.

But 16 comes before 17...

**Comment by rtzoeller** [comment]
@csjall all review feedback has been addressed.

**Comment by csjall** [comment]
- [ ] `Initialize Main Page.vi': Connect the error wire. Don't eat incoming errors.
image

**Pull request merged**
