### PR TITLE
Speculatively fix #122

### LINKED ISSUE #122: Autodetect fails sometimes
Sometimes Autodetect fails with the following error:

image

**Steps to reproduce:**
1. Add SLSC Chassis to Sys def (I added a real one)
2. Select SLSC Switch as the custom device from the Modules section (for relevant modules)
3. Select one of the modules and Hit Autodetect
4. Notice that it works sometimes or for some modules but not always.

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add a 1 second delay during auto-detect after opening a session to the chassis but before enumerating the modules. It appears that this should fix #122.

### Why should this Pull Request be merged?

It appears this could be caused by the modules not being recognized by SLSC yet; EDS appears to wait for 1 second to allow this discovery to happen. We should do the same.

### What testing has been done?

Tested that auto-detect still works locally.

### CODE REVIEW

**Comment by rtzoeller** [comment]
@csjall we could instead try to find the module immediately, and if we fail wait a second and then try again. This would speed up the custom device in the ideal case where the module is found immediately.

However, I am not sure what sort of caching is done and whether this dual discovery would work.

**Comment by csjall** [comment]
- [ ] The EDS custom device address this issue in a similar fashion. In addition to waiting for mDNS to resolve, it also pings the chassis to see that it is active. See code snippet below. We should consider whether we want to ping the chassis as well.
image
- [ ] With the added duration we should put a busy indicator so the user does not think the system is frozen. I am not 100% sure when/how EDS puts up the indicator, so check with Alex how he does it.

**Comment by buckd** [comment]
> With the added duration we should put a busy indicator so the user does not think the system is frozen. I am not 100% sure when/how EDS puts up the indicator, so check with Alex how he does it.

Pretty sure the `Enable System Explorer Update Buffer.vi` and `Commit System Explorer Update Buffer.vi` are what create the busy indicator. I think it probably happens in `SLSC Create Tree Hierarchy.vi`. There may be multiple places he does this, but this is probably the main one.

image

**Comment by rtzoeller** [comment]
@csjall our buttons are all currently actions, which means they launch a VI. It appears that we cannot set busy from an action, but we can set busy from the main page itself.

We could convert the actions to notifications, which would push the button handling logic into the main page.

Do you want me to convert the autodetect action to a notification, or submit this fix without set busy?

**Comment by csjall** [comment]
> @csjall our buttons are all currently actions, which means they launch a VI. It appears that we cannot set busy from an action, but we can set busy from the main page itself.
> 
> We could convert the actions to notifications, which would push the button handling logic into the main page.
> 
> Do you want me to convert the autodetect action to a notification, or submit this fix without set busy?

Submit the changes as is for now. If we find a reason to use notifications, then we can add the busy indicators to the main page.

**Pull request merged**
