### PR TITLE
Add and Remove Aliases from Endpoint Aliases Page

### PR DESCRIPTION
**Pull request by buckd**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Enables a user to add or remove aliases from the `Endpoint Aliases` page is System Explorer.

### Why should this Pull Request be merged?

This change will let users see the list of all available endpoints in their system and choose a valid endpoint to alias instead of having to script everything.

### What testing has been done?

Built and ran manual tests. Ran automated tests.

### CODE REVIEW

**Comment by rtzoeller** [comment]
- [ ] Fix typo "aleady" -> "already" 
image.

- [ ] We might want to put the alias and endpoint names in quotes, to help in the case where the endpoint name is empty. 
image

**Comment by rtzoeller** [comment]
- [ ] The text fields should be single-line, and ideally support tabbing between them (not sure if this is possible).

**Comment by buckd** [comment]
> The text fields should be single-line, and ideally support tabbing between them (not sure if this is possible).

You should be able to tab between items at the same array index. Enforcing single-line and tabbing between array elements is doable, but not trivial. I'd rather track that as an `enhancement` issue and not try to put it in this change.

**Comment by csjall** [comment]
> * [ ]  The text fields should be single-line, and ideally support tabbing between them (not sure if this is possible).

image

**Comment by csjall** [comment]
- [ ] Detect incoming errors and do no thing in the error case.
image
image

**Pull request merged**
