### PR TITLE
Display errors when hardware configuration changes

### PR DESCRIPTION
**Pull request by buckd**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Provides validation code to verify that any existing configuration in the Routing and Faulting custom device is valid. The validation code can be called from a scripting environment and is executed on load of any page in the Routing and Faulting custom device.

If errors are detected, the System Explorer error glyph will show that there are errors and descriptions of the invalid items will show up in the error window.

If hardware configuration or routing and faulting configuration is changed, all errors are cleared and validation is re-run so anything that is no longer an error is removed.

### Why should this Pull Request be merged?

It can be very difficult for users to track down what has changed when hardware is removed from the system or the hardware configuration changes. If the Routing and Faulting custom device has references to these hardware items, we can determine what is no longer valid and save lots of debugging time.

### What testing has been done?

Ran automated tests.
Configured system definition manually and verified errors are evaluated for each page load and correct error messages are given. Also checked that fixed errors are removed.

### CODE REVIEW

**Comment by csjall** [comment]
- [ ] Return hardware information from Validate so that we can reuse it for Routing Channel Page. Make `Find Missing Hardware Identifiers.vi` private instead of public.
image
- [ ] Reroute the crossed wires.
image

**Comment by rtzoeller** [comment]
- [ ] Are we intentionally not wiring errors up in the OnLoad action? If so, consider adding a comment explaining why.
image
- [ ] Should the `Module Connection Information` terminal in `Validate from Module Connection Information` be required?
- [ ] You can remove the indexing blocks in `Validate From Module Connection Information`. 
image

**Comment by rtzoeller** [comment]
- [ ] `Validate Custom Device Configuration.vi`: You can use a strict typedef on the VI reference to avoid duplicating the connector pane. 
image
image

**Comment by buckd** [comment]
Note that right now, because validation always happens, any time you change the page in the Routing and Faulting custom device, you will get a dirty dot on the system definition. There is a subsequent PR coming that only validates when needed and will address this issue.

**Comment by csjall** [comment]
- [ ] Move Validate into SubVIs virtual folder.
image

**Pull request merged**
