### PR TITLE
Add initial compiled data control

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This is a speculative attempt at the compiled data control, with the intent of allowing future engine and system explorer work to take place in parallel.

### Why should this Pull Request be merged?

This change should help us work more efficiently, and is a good first attempt at what the control will look like in the end.

### What testing has been done?

Ran SLSC Switch custom device unit tests.

### CODE REVIEW

**Comment by csjall** [comment]
- [ ] We have types replicated in the Scripting API. In the shared library you call them Channel Configuration. In the scripting API we call them Endpoint Configuration. Since Scripting API is tightly coupled with the custom device, we should consider using the types from the shared library if possible.

**Comment by rtzoeller** [comment]
@csjall I'm torn on this.

On one hand, I don't like duplicating the types. 

OTOH, the "endpoint" terminology was chosen to differentiate from VeriStand channels. I feel that distinction does not need to be made here since the implementation make it clear, and more importantly I feel the terminology we use here should align with the driver's. 

Using "endpoint" feels like a veneer that belongs in the public API, but I'm not sure it belongs in the engine.

@buckd thoughts?

**Comment by csjall** [comment]
> @csjall I'm torn on this.
> 
> On one hand, I don't like duplicating the types.
> 
> OTOH, the "endpoint" terminology was chosen to differentiate from VeriStand channels. I feel that distinction does not need to be made here since the implementation make it clear, and more importantly I feel the terminology we use here should align with the driver's.
> 
> Using "endpoint" feels like a veneer that belongs in the public API, but I'm not sure it belongs in the engine.
> 
> @buckd thoughts?

Let's move the endpoint configuration typedefs from the scripting library into the shared library. Update all callers to use the typedefs from the shared library.

**Comment by rtzoeller** [comment]
Unit tests are currently failing after I rebased my changes, but this appears to be an unrelated issue.

**Pull request merged**
