### PR TITLE
Routing and Faulting should come after NI-SWITCH custom devices

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Routing and Faulting now attempts to move itself after NI-SWITCH and other hardware custom devices in the system definition, and fails to compile if this fails (e.g. due to a scripted configuration being incorrect).

### Why should this Pull Request be merged?

The process of creating communication queues between custom devices requires that R+F is created second. This is implicitly true compared to SLSC Switch, but regular custom devices require special handling.

If Routing and Faulting is started before a custom device which receives messages during initialization, Routing and Faulting will time out fail to deploy correctly.

### What testing has been done?

Local testing, including editing the XML to emulate a scripted system definition.

### CODE REVIEW

**Review by buckd — COMMENTED** [review]
- [ ] In `Validate Custom Device Order.vi`, just use **Search 1D Array** instead of using the for loop and conditional. Same for `Fix Custom Device Order.vi`.
image
- [ ] In `Validate Custom Device Order.vi`, I'm not sure I understand why **Reverse 1D Array** is in there. Can it be removed?

**Comment by rtzoeller** [comment]
@buckd good catch on the loops. They originally had some additional logic and weren't cleaned up fully when that logic was removed.

The reversal is intentional. We're trying to find the _last_ hardware CD, so searching from the end make sense. The check on each element is just non-trivial enough (reading multiple properties) that I think reversing the array is worthwhile.

**Comment by rtzoeller** [comment]
@buckd I misread your message. We can indeed remove the reverse in `Validate Custom Device Order.vi`, just not in `Fix Custom Device Order.vi`.

**Comment by buckd** [comment]
> @buckd I misread your message. We can indeed remove the reverse in `Validate Custom Device Order.vi`, just not in `Fix Custom Device Order.vi`.

Yeah, I just happened to review `Validate Custom Device Order.vi` before `Fix Custom Device Order.vi`. The latter made sense, but I didn't have context for the former and where that code may have come from.

**Review by buckd — APPROVED** [review]

**Pull request merged**
