### PR TITLE
add dummy menu files to remove custom device scripting APIs from RT palettes

### PR DESCRIPTION
**Pull request by dbendele**
(reference https://ni.visualstudio.com/DevCentral/_workitems/edit/1138446)

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This pull request fixes Bug 1138446 (https://ni.visualstudio.com/DevCentral/_workitems/edit/1138446).

### Why should this Pull Request be merged?

Removes custom device scripting API palettes from RT palettes. Scripting VIs don't make sense on RT VIs and are broken. The dummy palette file (dir.mnu) is empty and the description has been updated to "VeriStand Custom Device Scripting APIs are not supported in VIs that run on real-time targets."

### What testing has been done?

Replacement menu files verified on vsecotest04 for Linux ARM, PXI Linux, and Pharlap targets. Verified that updated package ("\\nirvana\Measurements\VeriStandAddons\routing_and_faulting_custom_device\ni\export\PR-213\Build 1\2020\installer\ni-veristand-2020-custom-device-labview-support-common_0.0.0.1_windows_x64.nipkg") installs all expected menu files.

### CODE REVIEW

**Comment by dbendele** [comment]
Note to reviewers, the Targets\*\dir.mnu files all have the same icon and name as the original palette, but the items have been removed and the description updated.

image

**Comment by dbendele** [comment]
My Computer VI palette:
image

RT VI (Linux PXI, Pharlap, Linux ARM):
image

**Comment by dbendele** [comment]
Donovan and I had discussed (and even agreed) to an alternative implementation using a new dummy dir.mnu and relying on a Post Build Action VI to duplicate that file. On further inspection, it was found that the existing common dir.mnu is not exported as part of any of the existing build specs and is entirely contained within a dedicated package. To isolate this PR change, I added three identical dir.mnu files and updated the build.toml file for this dedicated package.

**Review by niphilj — APPROVED** [review]

**Comment by rtzoeller** [comment]
These .mnu files are only present in this repository for historical reasons. As you pointed out, they are only trivially associated with the repo (no build steps).

@buckd is this change the motivation we need to move them to another repository? I.e. https://github.com/ni/niveristand-custom-device-development-tools.

**Comment by buckd** [comment]
> is this change the motivation we need to move them to another repository? I.e. https://github.com/ni/niveristand-custom-device-development-tools.

I think we should move the `.mnu` files to a different repository, but this change can go here first. We should create a tech debt item to move them. The development tools repo isn't pulled into the release feed, so we would need to do some work to pull only  that package into the feed. Although those changes are not large, I'd like to make them all at the same time.

**Review by rtzoeller — APPROVED** [review]

**Comment by buckd** [comment]
@rtzoeller Work item 1163796 created.

**Review by buckd — APPROVED** [review]

**Comment by dbendele** [comment]
> I think we should move the `.mnu` files to a different repository, but this change can go here first. We should create a tech debt item to move them. The development tools repo isn't pulled into the release feed, so we would need to do some work to pull only that package into the feed. Although those changes are not large, I'd like to make them all at the same time.

Tech Debt item created: https://dev.azure.com/ni/DevCentral/_workitems/edit/1163797

**Pull request merged**
