### PR TITLE
Single source module paths, allowing for better rename handling

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Change the persisted format for aliases and connections to no longer refer to a module directly. Instead, the aliases and connections refer to a unique module identifier (currently a number), which allows us to use dependent node properties to automatically track path changes. 

For example, consider a state which was persisted as follows.

```xml
<Elem Key="Fault to Ground">
  <StringArray>
    <Elem>Targets/Controller/Hardware/SLSC/Downstairs/Modules/Slot 2 (SLSC Switch)/DUT_Ch0,Targets/Controller/Hardware/SLSC/Downstairs/Modules/Slot 2 (SLSC Switch)/BusA</Elem>
  </StringArray>
</Elem>
```

It is now persisted as follows, with an additional property tree hanging off the root custom device indicating where each module identifier maps.

```xml
<Elem Key="Fault to Ground">
  <StringArray>
    <Elem>0,DUT_Ch0,BusA</Elem>
  </StringArray>
</Elem>
```
```xml
<Property Name="user.CD.Modules"> <!-- On the custom device root-->
  <StringArray>
    <Elem>0</Elem>
  </StringArray>
</Property>
<Property Name="user.CD.Modules.0">
  <DependentNode Path="Targets/Controller/Hardware/SLSC/Downstairs/Modules/Slot 2 (SLSC Switch)" />
</Property>
```

Update the aliases scripting accessors to use a cluster, instead of a concatenated string for the endpoint name. This makes them more consistent with the state configuration workflow, and simplifies the implementation of this pull request.

We currently do not do any cleanup of the module properties when they are no longer referenced; this can be changed in a backwards compatible way in the future.

This pull request replaces #147.

### Why should this Pull Request be merged?

This allows the Routing and Faulting custom device to continue working even when the paths to the hardware custom devices change.

### What testing has been done?

Updated unit tests. Hand testing of the UI, including renaming chassis and modules which are referenced by the Routing and Faulting custom device.

The import/export tests are currently failing, due to bugs in the Advanced System Definition API. I will follow up with a pull request on https://github.com/NIVeriStandAdd-Ons/VeriStand-Addon-System-Definition-Utilities to fix those issues.

### CODE REVIEW

**Comment by rtzoeller** [comment]
@csjall The changes made to support the updated aliases format are mostly trivial modifications, but due to the number of files touched overwhelm this pull request. I would recommend starting by looking at the files touched by the commits (but at their latest version), before moving on to looking at the files touched by the alias support.


```
λ git diff master 67016d5af5d024cfd63d59f2b7b9149fb454e5a0 --name-status
M       Source/Routing and Faulting/Scripting/Constants/Scripting Constants.vi
M       Source/Routing and Faulting/Scripting/Routing Channel/Add Connection to State.vi
M       Source/Routing and Faulting/Scripting/Routing Channel/Add State (to Dictionaries).vi
M       Source/Routing and Faulting/Scripting/Routing Channel/Get Routing Channel State Configurations.vi
M       Source/Routing and Faulting/Scripting/Routing Channel/Get State from Routing Channel.vi
M       Source/Routing and Faulting/Scripting/Routing Channel/Remove State Connection.vi
M       Source/Routing and Faulting/Scripting/Routing Channel/Set Routing Channel State Configurations.vi
M       Source/Routing and Faulting/Scripting/Routing and Faulting Scripting.lvlib
A       Source/Routing and Faulting/Scripting/Utility/Add Module.vi
M       Source/Routing and Faulting/Scripting/Utility/Connection to String.vi
M       Source/Routing and Faulting/Scripting/Utility/Connections to Strings.vi
A       Source/Routing and Faulting/Scripting/Utility/Create Unique Module Identifier.vi
A       Source/Routing and Faulting/Scripting/Utility/Get Module Identifier.vi
A       Source/Routing and Faulting/Scripting/Utility/Get Module Identifiers.vi
A       Source/Routing and Faulting/Scripting/Utility/Get Module Path.vi
A       Source/Routing and Faulting/Scripting/Utility/Get Module Property Name.vi
A       Source/Routing and Faulting/Scripting/Utility/Get Routing and Faulting Parent Ref.vi
M       Source/Routing and Faulting/Scripting/Utility/String to Connection.vi
M       Source/Routing and Faulting/Scripting/Utility/Strings to Connections.vi
```

**Comment by csjall** [comment]
- [ ] Use the blue wire for the Routing and Faulting reference instead of the sea green wire. The sea green wire (or .NET reference type) has additional requirement that the caller needs to close the reference when they are done with it. By removing this burden from the caller we are less likely to introduce leaks.
image
- [ ] Fix obscured wiring.
image
- [ ] Please mutate test assets to reflect the new format.

**Comment by rtzoeller** [comment]
Regarding the following comment:

> We currently do not do any cleanup of the module properties when they are no longer referenced; this can be changed in a backwards compatible way in the future.

Two ideas were discussed; one was that we add reference counting to track how many connections/aliases were using a module, and the other was that we enumerate all connections and aliases periodically and check which are not in use.

I punted on this previously because the first idea has significant implementation complexity, and the second is expensive to do in isolation.

However, I believe that once @buckd adds support for adding errors to the system definition based on invalid connections/aliases, we will already be doing this enumeration of all connections/aliases. This provides us a nice opportunity to clean up unused module properties.

**Comment by rtzoeller** [comment]
> - [ ]  D.R.Y. Create a subVI to check for existence of module and adding module if not found.

I do not believe this is applicable if we combine the logic in Add and Set Alias. After this consolidation, Add Module is called in two places, but it is used in different ways (conditionally in Connection to String).

**Comment by csjall** [comment]
Sibmit these changes as is. Once we fix Advanced SysDef API, then import/export tests should start working again.

**Pull request merged**
